/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface BondingCurveInterface extends utils.Interface {
  functions: {
    "calculatePurchaseReturn(uint256,uint256,uint32,uint256)": FunctionFragment;
    "calculateSaleReturn(uint256,uint256,uint32,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "calculatePurchaseReturn" | "calculateSaleReturn"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calculatePurchaseReturn",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateSaleReturn",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculatePurchaseReturn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateSaleReturn",
    data: BytesLike
  ): Result;

  events: {};
}

export interface BondingCurve extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BondingCurveInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    calculatePurchaseReturn(
      _supply: PromiseOrValue<BigNumberish>,
      _reserveBalance: PromiseOrValue<BigNumberish>,
      _reserveRatio: PromiseOrValue<BigNumberish>,
      _depositAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calculateSaleReturn(
      _supply: PromiseOrValue<BigNumberish>,
      _reserveBalance: PromiseOrValue<BigNumberish>,
      _reserveRatio: PromiseOrValue<BigNumberish>,
      _sellAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  calculatePurchaseReturn(
    _supply: PromiseOrValue<BigNumberish>,
    _reserveBalance: PromiseOrValue<BigNumberish>,
    _reserveRatio: PromiseOrValue<BigNumberish>,
    _depositAmount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculateSaleReturn(
    _supply: PromiseOrValue<BigNumberish>,
    _reserveBalance: PromiseOrValue<BigNumberish>,
    _reserveRatio: PromiseOrValue<BigNumberish>,
    _sellAmount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    calculatePurchaseReturn(
      _supply: PromiseOrValue<BigNumberish>,
      _reserveBalance: PromiseOrValue<BigNumberish>,
      _reserveRatio: PromiseOrValue<BigNumberish>,
      _depositAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateSaleReturn(
      _supply: PromiseOrValue<BigNumberish>,
      _reserveBalance: PromiseOrValue<BigNumberish>,
      _reserveRatio: PromiseOrValue<BigNumberish>,
      _sellAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    calculatePurchaseReturn(
      _supply: PromiseOrValue<BigNumberish>,
      _reserveBalance: PromiseOrValue<BigNumberish>,
      _reserveRatio: PromiseOrValue<BigNumberish>,
      _depositAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateSaleReturn(
      _supply: PromiseOrValue<BigNumberish>,
      _reserveBalance: PromiseOrValue<BigNumberish>,
      _reserveRatio: PromiseOrValue<BigNumberish>,
      _sellAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    calculatePurchaseReturn(
      _supply: PromiseOrValue<BigNumberish>,
      _reserveBalance: PromiseOrValue<BigNumberish>,
      _reserveRatio: PromiseOrValue<BigNumberish>,
      _depositAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateSaleReturn(
      _supply: PromiseOrValue<BigNumberish>,
      _reserveBalance: PromiseOrValue<BigNumberish>,
      _reserveRatio: PromiseOrValue<BigNumberish>,
      _sellAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
