/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AddressRegistry } from "./AddressRegistry";
export type { RevestAccessControl } from "./RevestAccessControl";
