/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  BondingCurve,
  BondingCurveInterface,
} from "../../../../contracts/bonding-curve/EminenceCurrencyHelpers.sol/BondingCurve";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        internalType: "uint256",
        name: "_supply",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_reserveBalance",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "_reserveRatio",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "_depositAmount",
        type: "uint256",
      },
    ],
    name: "calculatePurchaseReturn",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "uint256",
        name: "_supply",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_reserveBalance",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "_reserveRatio",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "_sellAmount",
        type: "uint256",
      },
    ],
    name: "calculateSaleReturn",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class BondingCurve__factory {
  static readonly abi = _abi;
  static createInterface(): BondingCurveInterface {
    return new utils.Interface(_abi) as BondingCurveInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BondingCurve {
    return new Contract(address, _abi, signerOrProvider) as BondingCurve;
  }
}
