/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IUniswapFactory,
  IUniswapFactoryInterface,
} from "../../../../contracts/side-entrance/CallOptions.sol/IUniswapFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "getPair",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IUniswapFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IUniswapFactoryInterface {
    return new utils.Interface(_abi) as IUniswapFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUniswapFactory {
    return new Contract(address, _abi, signerOrProvider) as IUniswapFactory;
  }
}
