/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as masterChefSol from "./MasterChef.sol";
export { MulaToken__factory } from "./MulaToken__factory";
