/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as assetWrapperSol from "./AssetWrapper.sol";
export { AssetHolder__factory } from "./AssetHolder__factory";
export { GameAsset__factory } from "./GameAsset__factory";
