/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAdvisor,
  IAdvisorInterface,
} from "../../../../contracts/freebie/RewardsAdvisor.sol/IAdvisor";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "delegatedTransferERC20",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAdvisor__factory {
  static readonly abi = _abi;
  static createInterface(): IAdvisorInterface {
    return new utils.Interface(_abi) as IAdvisorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAdvisor {
    return new Contract(address, _abi, signerOrProvider) as IAdvisor;
  }
}
