/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as bondingCurve from "./bonding-curve";
export * as degenJackpot from "./degen-jackpot";
export * as extractoor from "./extractoor";
export * as flashLoaner from "./flash-loaner";
export * as freeLunch from "./free-lunch";
export * as freebie from "./freebie";
export * as gameAssets from "./game-assets";
export * as governanceShenanigans from "./governance-shenanigans";
export * as inflationaryNetWorth from "./inflationary-net-worth";
export * as jpegSniper from "./jpeg-sniper";
export * as malleable from "./malleable";
export * as nftBonanza from "./nft-bonanza";
export * as opynSesame from "./opyn-sesame";
export * as other from "./other";
export * as safuSwapper from "./safu-swapper";
export * as safuVault from "./safu-vault";
export * as safuWallet from "./safu-wallet";
export * as sideEntrance from "./side-entrance";
export * as tastyStake from "./tasty-stake";
