/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as safuPoolSol from "./SafuPool.sol";
export type { safuPoolSol };
export type { SafuUtils } from "./SafuUtils";
