/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as safuVaultSol from "./SafuVault.sol";
export type { safuVaultSol };
export type { SafuStrategy } from "./SafuStrategy";
