/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assetWrapperSol from "./AssetWrapper.sol";
export type { assetWrapperSol };
export type { AssetHolder } from "./AssetHolder";
export type { GameAsset } from "./GameAsset";
