/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as safuVaultSol from "./SafuVault.sol";
export { SafuStrategy__factory } from "./SafuStrategy__factory";
